server:
  host: localhost
  port: 8603
engine:
  faster-whisper:
    device: cpu
    beam_size: 5
  funasr:
    device: cpu
  sensevoice:
    device: cpu
model:
  faster-whisper:
    small:
      path: small
      compute_type: int8
      beam_size: 5